In [1]:
import scipy
from scipy.optimize import minimize
%matplotlib inline
import numpy as np
import math
import matplotlib.pyplot as plt
import ad

<h2> Exercise 5 </h2>

<break>
<h4> Task 1 </h4>
<p> In this task we will solve the optimization problem:: </p>

$$  \min \qquad   x_1^2 + x_2^2 $$
$$ \qquad  \text{s.t.}  \qquad x_1 + x_2 ≥ 1 $$



<p> We will solve the problem using just the optimality conditions </p>


Let us verify the KKT necessary conditions for the local minimum as:

Let's first define a Lagrangian function as follows:

$$ 𝐿(𝑥,𝜇,𝜆)= f(x)− 𝜇_1h(x) - 𝜆_1g(x) $$
And we will get:
$$ 𝐿(𝑥,𝜇,𝜆)=(x_1^2 + x_2^2) − 𝜇(0) - 𝜆(x_1 + x_2 - 1) $$
So
$$
𝐿(𝑥,𝜇,𝜆) = x_1^2 + x_2^2 + λ - λx_1 - λx_2
$$


Calculating partial derivatives we will get:
$$ \frac{\partial L}{\partial x_1} = 2x_1 - 𝜆 = 0$$
$$ $$
$$ \frac{\partial L}{\partial x_2} = 2x_2 - 𝜆 = 0$$

$$ \frac{\partial L}{\partial 𝜆} = 1 - x_1 - x_2 = 0 $$
$$ $$
$$ $$
From here we will get:
$$ 2x_1 - 𝜆 = 0$$
$$ 2x_2 - 𝜆 = 0$$
So
$$ x_1 = \frac{𝜆}{2}$$
$$ x_2 = \frac{𝜆}{2}$$

Thus
$$ -1 + \frac{𝜆}{2} + \frac{𝜆}{2} = 0 $$
$$ $$
$$  \frac{𝜆}{2} + \frac{𝜆}{2} = 1 $$
$$ $$
$$  \frac{2𝜆}{2} = 1 $$
$$ $$
$$ 𝜆 = 1 $$
We get that $ 𝜆 > 0 $ 
$$ $$
In this case, the inequality constraint is active and the optimal solution is on the boundary $x_1 + x_2 = 1$.

So the optimal solution is $ x_1 = x_2 = \frac{𝜆}{2}$ and the minimum value of the objective function is:.

 x* = [$\frac{1}{2}$,$\frac{1}{2}$]

<h4> Task 2 </h4>
<p> In this task we consider a problem: </p>
$$
\begin{equation}
\begin{aligned}
  \min \qquad & f(x) \\
 \text{s.t.}\qquad & h_k(x) = 0 \\
  \qquad & \textit{for all } k = 1,...K \\
\end{aligned}
\end{equation}
$$
<p> and all of the functions are twice differentiable </p>
<p> We need to show that the gradient of hte augmented Lagrangian function is zero in the minimizer $x^*$ of the above problem </p>
<break>
<p> In other words, let's show that: </p>
    
$$
\begin{equation}
\begin{aligned}
  & \nabla_x L_c(x^*, \lambda^*) = 0 \\
 & \text{where } \lambda^* \in R^n \\
\end{aligned}
\end{equation}
$$
    <p> is the corresponding optimal Lagrange multiplier vector </p>

We will define Lagrange function as follows:
$$ L(𝑥,𝜆) = 𝑓(𝑥) + Σ_{𝑘=1}^𝐾 (𝜆_𝑘  ℎ_𝑘(𝑥)) + (\frac{𝜇}{2}) Σ_{𝑘=1}^𝐾 (ℎ_𝑘(𝑥))^2 = 0$$

Now we will take partial derivatives:
$$
\frac{\partial L(𝑥^*,𝜆^*)}{\partial x} = \frac{\partial 𝑓(𝑥^*)}{\partial x} + Σ_{𝑘=1}^𝐾 𝜆_𝑘^*  \frac{\partial ℎ_𝑘(𝑥^*)}{\partial 𝑥} + 𝜇  Σ_{𝑘=1}^𝐾 ℎ_𝑘(𝑥^*)  \frac{\partial ℎ_𝑘(𝑥^*)}{\partial x} = 0
$$

Since $𝑥^*$ is the minimizer of the optimization problem, we know that $ \frac{\partial 𝑓(𝑥^*)}{\partial x}= 0$.

We also know that $ \frac{\partial ℎ_𝑘(𝑥^*)}{\partial 𝑥} = 0 $ for all $𝑘$ because $𝑥^*$ satisfies all the constraints.

Therefore, the equation simplifies to:

$$
\frac{\partial L(𝑥^*,𝜆^*)}{\partial x} =   𝜇 Σ_{𝑘=1}^𝐾 ℎ_𝑘(𝑥^*)  \frac{\partial ℎ_𝑘(𝑥^*)}{\partial x} = 0
$$

Since $𝑥^*$ satisfies all the constraints, we know that $ℎ_𝑘(𝑥^*) = 0$ for all $𝑘$.

Thus

$$
\begin{equation}
\begin{aligned}
  & \nabla_x L_c(x^*, \lambda^*) = 0 \\
 & \text{where } \lambda^* \in R^n \\
\end{aligned}
\end{equation}
$$


<h4> Task 3 </h4>
<p> For tasks 3 and 4 we study the optimization problem: </p>

$$
\begin{equation}
\begin{aligned}
  \min \qquad & x_1^2 + x_2^2 + x_3^2 + (1-x_4)^2 \\
 \text{s.t.}\qquad & x_1^2 + x_2^2 -1 = 0 \\
  \qquad & x_1^2 + x_3^2 - 1 = 0 \\
  \qquad & x \in R^4 
\end{aligned}
\end{equation}
$$

<p> In this task we will be using the SQP method to solve above problem </p>

In [10]:
def f(x):
    return x[0]**2 + x[1]**2 + x[2]**2 +(1 - x[3])**2, [], [x[0]**2 + x[1]**2 - 1, x[0]**2 + x[2]**2 - 1]

In [11]:
#SQP code from lectures:

#if k=0, returns the gradient of lagrangian, if k=1, returns the hessian
def diff_L(f,x,l,k):
    #Define the lagrangian for given f and Lagrangian multiplier vector l
    L = lambda x_: f(x_)[0] + (np.matrix(f(x_)[2])*np.matrix(l).transpose())[0,0]
    return ad.gh(L)[k](x)

#Returns the gradients of the equality constraints
def grad_h(f,x):
    return  [ad.gh(lambda y:
                   f(y)[2][i])[0](x) for i in range(len(f(x)[2]))] 

#Solves the quadratic problem inside the SQP method
def solve_QP(f,x,l):
    left_side_first_row = np.concatenate((\
    np.matrix(diff_L(f,x,l,1)),\
    np.matrix(grad_h(f,x)).transpose()),axis=1)
    left_side_second_row = np.concatenate((\
    np.matrix(grad_h(f,x)),\
    np.matrix(np.zeros((len(f(x)[2]),len(f(x)[2]))))),axis=1)
    right_hand_side = np.concatenate((\
    -1*np.matrix(diff_L(f,x,l,0)).transpose(),
    -np.matrix(f(x)[2]).transpose()),axis = 0)
    left_hand_side = np.concatenate((\
                                    left_side_first_row,\
                                    left_side_second_row),axis = 0)
    temp = np.linalg.solve(left_hand_side,right_hand_side)
    return temp[:len(x)],temp[len(x):] # update for both x and l
    
def SQP(f,start,precision):
    x = start
    l = np.ones(len(f(x)[2])) # initialize Lagrange multiplier vector l as a vector of 1s
    f_old = float('inf')
    f_new = f(x)[0]
    while abs(f_old-f_new)>precision:
        print(x)
        f_old = f_new
        (p,v) = solve_QP(f,x,l) # obtain updates for x and l by solving the quadratic subproblem
        x = x+np.array(p.transpose())[0] # update the solution x 
        l = l+v # update the Lagrange multipliers l
        f_new = f(x)[0]
    return x


In [37]:
x1 = [0.01, 1.5, 0.1, 1]
#print(f(x))
res = SQP(f, x1, 0.0001)
print("res: ", res)

x2 = [0.0001, 1.9, 0.001, -1]
res = SQP(f, x2, 0.0001)
print("res: ", res)

[0.01, 1.5, 0.1, 1]
[0.33924329 1.08110504 5.01657567 1.        ]
[1.62688451 0.54576326 2.50941078 1.        ]
[ 1.5677837  -1.05961264  0.96490572  1.        ]
[ 1.23098012 -0.34017315  0.27420692  1.        ]
[ 1.05269127 -0.057832   -0.00215631  1.        ]
[ 1.00132387 -0.02882187  0.00144634  1.        ]
[ 1.00000785 -0.01416875 -0.00410297  1.        ]
[1.00011732 0.0011959  0.02654271 1.        ]
[ 1.00000983 -0.00762093  0.01290105  1.        ]
[ 1.00000301 -0.00341611  0.00621757  1.        ]
res:  [1.00000842e+00 7.55691872e-04 1.75513131e-03 1.00000000e+00]
[0.0001, 1.9, 0.001, -1]
[ 33.11265845   1.21141513 496.68923916   1.        ]
[ 1.66019634e+01 -2.28910831e-01  2.48342584e+02  1.00000000e+00]
[8.33292475e+00 1.79858635e-02 1.24171170e+02 1.00000000e+00]
[ 4.22648594e+00 -5.62332449e-04  6.20855836e+01  1.00000000e+00]
[ 2.23154460e+00 -2.90548367e-06  3.10427918e+01  1.00000000e+00]
[ 1.33983235e+00 -2.06866592e-07  1.55213959e+01  1.00000000e+00]
[ 1.04309719e+00 -3

I tested this with couple different starting values and it seems like we would need a really good starting point
to get accurate optimals using SQP

<h4> Task 4 </h4>
<p> In this task we will be using the Lagrangian method to solve the optimization problem </p>

In [35]:
#Augmented Lagrangian method from lectures:

def augmented_langrangian(f,x,la,c):
    second_term = float(numpy.matrix(la)*numpy.matrix(f(x)[2]).transpose())
    third_term = 0.5*c*numpy.linalg.norm(f(x)[2])**2
    return f(x)[0]+second_term+third_term

def augmented_langrangian_method(f,start,la0,c0):
    x_old = [float('inf')]*2
    x_new = start
    f_old = float('inf')
    f_new = f(x_new)[0]
    la = la0
    c = c0
    steps = []
    while abs(f_old-f_new)>0.00001:
#    while numpy.linalg.norm(f(x_new)[2])>0.00001: # doesn't work as itself, see starting from any feasible point
        res = minimize(lambda x:augmented_langrangian(f,x,la,c),x_new)
        x_old = x_new
        f_old = f_new
        la = float(la+numpy.matrix(c)*numpy.matrix(f(res.x)[2]).transpose()) # update Lagrangian
        x_new = res.x
        f_new = f(x_new)[0]
        c = 2*c # increase the penalty coefficient
        steps.append(list(x_new))
    return x_new,c, steps

In [36]:
x1 = [0.01, 1.5, 0.1, 1]
#print(f(x))
res = SQP(f, x1, 0.0001)
print("res: ", res)

x2 = [0.0001, 1.9, 0.001, -1]
res = SQP(f, x2, 0.0001)
print("res: ", res)

[0.01, 1.5, 0.1, 1]
[0.33924329 1.08110504 5.01657567 1.        ]
[1.62688451 0.54576326 2.50941078 1.        ]
[ 1.5677837  -1.05961264  0.96490572  1.        ]
[ 1.23098012 -0.34017315  0.27420692  1.        ]
[ 1.05269127 -0.057832   -0.00215631  1.        ]
[ 1.00132387 -0.02882187  0.00144634  1.        ]
[ 1.00000785 -0.01416875 -0.00410297  1.        ]
[1.00011732 0.0011959  0.02654271 1.        ]
[ 1.00000983 -0.00762093  0.01290105  1.        ]
[ 1.00000301 -0.00341611  0.00621757  1.        ]
res:  [1.00000842e+00 7.55691872e-04 1.75513131e-03 1.00000000e+00]
[0.0001, 1.9, 0.001, -1]
[ 33.11265845   1.21141513 496.68923916   1.        ]
[ 1.66019634e+01 -2.28910831e-01  2.48342584e+02  1.00000000e+00]
[8.33292475e+00 1.79858635e-02 1.24171170e+02 1.00000000e+00]
[ 4.22648594e+00 -5.62332449e-04  6.20855836e+01  1.00000000e+00]
[ 2.23154460e+00 -2.90548367e-06  3.10427918e+01  1.00000000e+00]
[ 1.33983235e+00 -2.06866592e-07  1.55213959e+01  1.00000000e+00]
[ 1.04309719e+00 -3

I tested this method too with some different starting values. And it seems like this has same problems as SQP.
It seems like we would need a really good starting point to get good optimal answer